source 'https://rubygems.org'

gem 'httparty'
gem 'rest-client'
gem 'json'
gem 'pg'
gem 'pry'
gem 'omniauth'
gem 'omniauth-oauth2', '~> 1.3.1'
gem 'omniauth-spotify'
gem 'rake'
gem 'rspotify'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib', :require => false
gem 'sinatra-flash'
gem 'shotgun'
gem 'thin'
